
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, tidyverse)
#Importing data
transaction <- read.csv("~/Wemanity/transaction")
#Eliminating first column (indexes generated by previous sampling) & NA data
transactionData<-na.omit(transaction) 
transactionData$X<-NULL
#Changing column Names
names(transactionData)<-c("cardId" , "dateTime","siteCode", "siteDescription","checkoutCode",
                           "ticketNumber","productCode","productName","scanCode","amount","promotion",
                          "structureCode","alimentary","shelf")
#Changing siteDescription levels (the levels contain "_" which might cause processing problems)
levels(transactionData$siteDescription)<-c("site1","site2","site3","site4","site5")
